name: continuous-integration/gh-actions/gui

on: [push, pull_request]

jobs:
  build-macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: update brew and install dependencies
      run: brew update && brew install wget
    - name: wget
      run: wget http://download.qt.io/official_releases/qt/5.15/5.15.0/single/qt-everywhere-src-5.15.0.tar.xz
    - name: ter
      run: tar -xJf qt-everywhere-src-5.15.0.tar.xz
    - name: find
      run: find qt-everywhere-src-5.15.0
