name: continuous-integration/gh-actions/gui

on: [push, pull_request]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: eine/setup-msys2@v0
      with:
        update: true
    - name: install monero dependencies
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git mingw-w64-x86_64-qt5 mingw-w64-x86_64-libgcrypt
    - name: build
      run: msys2do DEV_MODE=1 make release-win64
    - name: test qml
      run: msys2do build/release/bin/monero-wallet-gui --test-qml
